// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Analytics: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/icons/analytics.vue')['default']
    Animals: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/icons/animals.vue')['default']
    Calendar: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/icons/calendar.vue')['default']
    Navbar: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/Navbar.vue')['default']
    Operations: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/icons/operations.vue')['default']
    Settings: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/icons/settings.vue')['default']
    Sidebar: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/Sidebar.vue')['default']
    Stalls: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/icons/stalls.vue')['default']
    Users: typeof import('D:/works-directory/vue projects/vite-vue2-typescript/src/components/icons/users.vue')['default']
  }
}

export { }
